### PR TITLE
[base.html] Alter `li`s to `p`s in link list

### PR DESCRIPTION
**Pull request by Olf0**

### CODE REVIEW

**Review by Olf0 — COMMENTED** [review]
LGTM

**Comment by HenkKalkwater** [comment]
I was wondering why you changed the `<li>`s to `<p>`s, since it breaks a few stylesheet rules that assume that `.link-list` contains `<li>s`:

https://github.com/sailfishos-chum/sailfishos-chum.github.io/blob/c2c63ce0d37d9a3ed752f392ef8c7bca89a5d98d/chumweb/www/static/style.css#L352-L365

and

https://github.com/sailfishos-chum/sailfishos-chum.github.io/blob/c2c63ce0d37d9a3ed752f392ef8c7bca89a5d98d/chumweb/www/static/style.css#L88-L91

Nitpick: perhaps you could also make the list items bold (#20) by adding a `font-weight: bold;` here

**Comment by Olf0** [comment]
BTW, because I am a "web-techniques idiot" (I was proficient in UNIX system administration and C-programming for microcontrollers 25 years ago), feel free to criticise anything which does not seem fit: I can only learn. :smiley:

**Comment by Olf0** [comment]
@HenkKalkwater, Chris I really do not intend to work against the concepts you implemented, hence if you denote how one can achieve a look which provides more vertical spacing between the list items than the simple line spacing (for details, [see here](https://github.com/sailfishos-chum/sailfishos-chum.github.io/pull/19#issuecomment-2015220041)), I will use that instead of paragraphs.

**Comment by HenkKalkwater** [comment]
Hey, sorry for the lack of communication, I was busy with other things. I'm not mad :). I've addressed it in #28. If that one looks alright, I'll merge that one in.

**Comment by Olf0** [comment]
> Hey, sorry for the lack of communication, I was busy with other things.

That is absolutely fine, I just wanted to make sure that I do not override your concerns / suggestions / criticism, because you are the principal author of this project and I only try to play the role of a quality-assurer.

> I'm not mad :).

Up to this surprising statement I would never have considered that, rather the opposite: You considerations, statements and actions appear to be clear, focused and comprehensible.
But if I take this statement of yours seriously: I never had the slightest doubt regarding your sanity, but impressions are very limited on the net.  If you really doubt your sanity, the are professionals who can perform checks and balances and might support you (if you wish) when mental issues burden you.  If you want a little more guidance, please let me know, but then we better establish a private channel (e.g. via XMPP / Jabber, Matrix or email; in this descending order of preference).

**Comment by HenkKalkwater** [comment]
Please read “I'm not mad” as in “I wasn't ignoring you on purpose”, I suppose I somewhat misinterpreted it. 

Op Maandag 15 april 2024 schreef olf:

**Comment by Olf0** [comment]
> Please read “I'm not mad” as in “I wasn't ignoring you on purpose”, I suppose I somewhat mistranslated it and I meant to use mad in the sense of angry or annoyed.

Oh, there is a subtle difference between "being mad" and "being mad at someone": the latter means being quite angry with someone ("angry *at* someone" is also valid and means the same).

> Sorry for the confusion

No worries!

**Pull request merged**
